import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar';
import LayoutContainer from '@/components/LayoutContainer';
import cn from '@/lib/utils';
const inter = Inter({ subsets: ['latin'] });




export const metadata: Metadata = {
  title: 'Flag Master\'s',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LayoutContainer>
      <body className={cn('min-h-screen w-full overflow-x-hidden bg-white dark:bg-slate-800 dark:text-white text-slate-900',inter.className)}>
        <Navbar />
        {children}</body>
        </LayoutContainer>
    </html>
  )
}
